version: '3.4'

networks:
  akka-network:
    driver: bridge

services:
  seed:
    image: ${DOCKER_REGISTRY}examplescenarios
    environment:
      IS_AKKA_SEED: "true"
      IS_PROD: "true"
    build:
      context: .
      dockerfile: ExampleScenarios/Dockerfile
    hostname: master
    networks:
      - akka-network

  prod:
    image: ${DOCKER_REGISTRY}examplescenarios
    environment:
      IS_AKKA_SEED: "false"
      IS_PROD: "true"
    build:
      context: .
      dockerfile: ExampleScenarios/Dockerfile
    networks:
      - akka-network
    links:
      - seed:master

  cons:
    image: ${DOCKER_REGISTRY}examplescenarios
    environment:
      IS_AKKA_SEED: "false"
      IS_PROD: "false"
    build:
      context: .
      dockerfile: ExampleScenarios/Dockerfile
    networks:
      - akka-network
    links:
      - seed:master


